export const LOGOUT_PROFILE = 'LOGOUT_PROFILE';

export const FETCH_ORDER_HISTORY = 'FETCH_ORDER_HISTORY';

export const FETCH_PROFILE = 'FETCH_PROFILE';

export const CHANGE_NEW_EMAIL ='CHANGE_NEW_EMAIL';

export const CHANGE_NEW_FIRST_NAME ='CHANGE_NEW_FIRST_NAME';

export const CHANGE_NEW_LAST_NAME ='CHANGE_NEW_LAST_NAME';

export const CHANGE_NEW_PHONE ='CHANGE_NEW_PHONE';

export const CHANGE_NEW_STREET ='CHANGE_NEW_STREET';

export const CHANGE_NEW_UNIT ='CHANGE_NEW_UNIT';

export const CHANGE_NEW_CITY ='CHANGE_NEW_CITY';

export const CHANGE_NEW_STATE ='CHANGE_NEW_STATE';

export const CHANGE_NEW_ZIP = 'CHANGE_NEW_ZIP';

export const SUBMIT_PROFILE_CHANGES = 'SUBMIT_PROFILE_CHANGES';

