export const LOGOUT_SUBSCRIPTION = 'LOGOUT_SUBSCRIPTION';

export const FETCH_PLAN_INFO = 'FETCH_PLAN_INFO';
export const CHOOSE_MEALS_EACH_DELIVERY = 'CHOOSE_MEALS_EACH_DELIVERY';
export const CHOOSE_PAYMENT_OPTION = 'CHOOSE_PAYMENT_OPTION';
export const GET_TOTAL_PAYMENT = 'GET_TOTAL_PAYMENT';

export const FETCH_PROFILE_INFO = 'FETCH_PROFILE_INFO'
export const CHANGE_ADDRESS_FIRST_NAME = 'CHANGE_ADDRESS_FIRST_NAME';
export const CHANGE_ADDRESS_LAST_NAME = 'CHANGE_ADDRESS_LAST_NAME';
export const CHANGE_ADDRESS_EMAIL = 'CHANGE_ADDRESS_EMAIL';
export const CHANGE_ADDRESS_STREET = 'CHANGE_ADDRESS_STREET';
export const CHANGE_ADDRESS_UNIT = 'CHANGE_ADDRESS_UNIT';
export const CHANGE_ADDRESS_CITY = 'CHANGE_ADDRESS_CITY';
export const CHANGE_ADDRESS_STATE = 'CHANGE_ADDRESS_STATE';
export const CHANGE_ADDRESS_ZIP = 'CHANGE_ADDRESS_ZIP';
export const CHANGE_ADDRESS_PHONE = 'CHANGE_ADDRESS_PHONE';
export const CHANGE_DELIVERY_INSTRUCTIONS = 'CHANGE_DELIVERY_INSTRUCTIONS';
export const CHANGE_PAYMENT_PASSWORD = 'CHANGE_PAYMENT_PASSWORD';
export const CHANGE_PAYMENT_CREDIT_CARD = 'CHANGE_PAYMENT_PASSWORD';
export const SUBMIT_PAYMENT = 'SUBMIT_PAYMENT';
