export const CHOOSE_PLAN_DAY = 'CHOOSE_PLAN_DAY';
export const CHOOSE_MEALS_EACH_DELIVERY = 'CHOOSE_MEALS_EACH_DELIVERY';
export const CHOOSE_PAYMENT_OPTION = 'CHOOSE_PAYMENT_OPTION';
export const CHANGE_PAYMENT_TOTAL = 'CHANGE_PAYMENT_TOTAL'